title: lsy96999
email: lsy96999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  lsy96999 blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  lsy96999

# Build settings
theme: minima
plugins:
  - jekyll-feed